name: Verify Code Owners

on: [push]

jobs:
  verify_code_owners:
    runs-on: ubuntu-latest
    name: A job to verify Code Owners in CODEOWNERS file against input.
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./verify-code-owners # Uses an action in the root directory
        with:
          code-owners: '@ktikku'